[2018-04-16 17:46:21] request.INFO: Matched route "get_profile". {"route":"get_profile","route_parameters":{"_controller":"AppBundle\\Controller\\RestProfileController::getAction","_format":"json","user":"1","_route":"get_profile"},"request_uri":"http://localhost/test1/web/app_acceptance.php/profile/1","method":"GET"} []
[2018-04-16 17:46:21] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-16 17:46:23] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in driver: SQLSTATE[HY000] [1049] Unknown database 'db_acceptance'" at C:\xampp\htdocs\test1\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1049] Unknown database 'db_acceptance' at C:\\xampp\\htdocs\\test1\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'db_acceptance' at C:\\xampp\\htdocs\\test1\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:50, PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'db_acceptance' at C:\\xampp\\htdocs\\test1\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:46)"} []
[2018-04-16 17:47:33] request.INFO: Matched route "get_profile". {"route":"get_profile","route_parameters":{"_controller":"AppBundle\\Controller\\RestProfileController::getAction","_format":"json","user":"1","_route":"get_profile"},"request_uri":"http://localhost/test1/web/app_acceptance.php/profile/1","method":"GET"} []
[2018-04-16 17:47:33] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-16 17:47:33] doctrine.DEBUG: SELECT t0.username AS username_1, t0.username_canonical AS username_canonical_2, t0.email AS email_3, t0.email_canonical AS email_canonical_4, t0.enabled AS enabled_5, t0.salt AS salt_6, t0.password AS password_7, t0.last_login AS last_login_8, t0.confirmation_token AS confirmation_token_9, t0.password_requested_at AS password_requested_at_10, t0.roles AS roles_11, t0.id AS id_12 FROM fos_user t0 WHERE t0.id = ? ["1"] []
[2018-04-16 17:47:33] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "" at C:\xampp\htdocs\test1\src\AppBundle\Controller\RestProfileController.php line 43 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0):  at C:\\xampp\\htdocs\\test1\\src\\AppBundle\\Controller\\RestProfileController.php:43)"} []
